set nocount on
SELECT 
      'USE [' + d.name + N']' + CHAR(13) + CHAR(10) 
    + 'DBCC SHRINKFILE (N''' + mf.name + N''' , 0, TRUNCATEONLY)' 
    + CHAR(13) + CHAR(10) + CHAR(13) + CHAR(10) 
FROM 
         sys.master_files mf 
    JOIN sys.databases d 
        ON mf.database_id = d.database_id 
WHERE d.database_id > 4 and mf.type_desc = 'LOG'

/*
Copy the output from above and execute (see below)
*/


USE [ReportServer]  DBCC SHRINKFILE (N'ReportServer_log' , 0, TRUNCATEONLY)    
USE [ReportServerTempDB]  DBCC SHRINKFILE (N'ReportServerTempDB_log' , 0, TRUNCATEONLY)    
USE [gp_test]  DBCC SHRINKFILE (N'gp_test_log' , 0, TRUNCATEONLY)    
USE [gp_car]  DBCC SHRINKFILE (N'gp_car_log' , 0, TRUNCATEONLY)    
USE [gp_rebs]  DBCC SHRINKFILE (N'gp_rebs_log' , 0, TRUNCATEONLY)    
USE [DYNAMICS]  DBCC SHRINKFILE (N'GPSDYNAMICSLog.ldf' , 0, TRUNCATEONLY)    
USE [TWO]  DBCC SHRINKFILE (N'GPSTWOLog.ldf' , 0, TRUNCATEONLY)    
USE [GTCAR]  DBCC SHRINKFILE (N'GPSGCARLog.ldf' , 0, TRUNCATEONLY)    
USE [GCAR]  DBCC SHRINKFILE (N'GPSGCARLog.ldf' , 0, TRUNCATEONLY)    
USE [GREBS]  DBCC SHRINKFILE (N'GPSGREBSLog.ldf' , 0, TRUNCATEONLY)    
USE [GTREB]  DBCC SHRINKFILE (N'GPSGREBSLog.ldf' , 0, TRUNCATEONLY)    
USE [ManagementReporter]  DBCC SHRINKFILE (N'ManagementReporter_Log' , 0, TRUNCATEONLY)    
USE [COA]  DBCC SHRINKFILE (N'GPSCOALog.ldf' , 0, TRUNCATEONLY)    
USE [GCREI]  DBCC SHRINKFILE (N'GPSGCREILog.ldf' , 0, TRUNCATEONLY)    
USE [GCREP]  DBCC SHRINKFILE (N'GPSGCREPLog.ldf' , 0, TRUNCATEONLY)    
USE [GCREF]  DBCC SHRINKFILE (N'GPSGCREFLog.ldf' , 0, TRUNCATEONLY)    
USE [GIMPA]  DBCC SHRINKFILE (N'GPSGIMPALog.ldf' , 0, TRUNCATEONLY)    
USE [GREBT]  DBCC SHRINKFILE (N'GPSGREBTLog.ldf' , 0, TRUNCATEONLY)    
USE [GRERS]  DBCC SHRINKFILE (N'GPSGRERSLog.ldf' , 0, TRUNCATEONLY)    
USE [Accounting]  DBCC SHRINKFILE (N'Accounting_Log' , 0, TRUNCATEONLY)    
USE [CarOrgRedesign]  DBCC SHRINKFILE (N'CarOrgRedesign_Log' , 0, TRUNCATEONLY)    
USE [Convio]  DBCC SHRINKFILE (N'Convio_Log' , 0, TRUNCATEONLY)    
USE [AX]  DBCC SHRINKFILE (N'AX_log' , 0, TRUNCATEONLY)    
USE [QuarterlyDuesStatements]  DBCC SHRINKFILE (N'QuarterlyDuesStatements_log' , 0, TRUNCATEONLY)    
USE [LegalHotline]  DBCC SHRINKFILE (N'LegalHotline_Log' , 0, TRUNCATEONLY)    
USE [Legislative]  DBCC SHRINKFILE (N'Legislative_Log' , 0, TRUNCATEONLY)    
USE [Login]  DBCC SHRINKFILE (N'Login_Log' , 0, TRUNCATEONLY)    
USE [MagTapes]  DBCC SHRINKFILE (N'MagTapes_Log' , 0, TRUNCATEONLY)    
USE [MemberDuesBilling]  DBCC SHRINKFILE (N'MemberDuesBilling_Log' , 0, TRUNCATEONLY)    
USE [Membership]  DBCC SHRINKFILE (N'Membership_Log' , 0, TRUNCATEONLY)    
USE [MeetingRegistration]  DBCC SHRINKFILE (N'MeetingRegistration_Log' , 0, TRUNCATEONLY)    
USE [I3_IC_V4]  DBCC SHRINKFILE (N'I3_IC_V4_Log' , 0, TRUNCATEONLY)    
USE [TrendsProd]  DBCC SHRINKFILE (N'TrendsProd_Log' , 0, TRUNCATEONLY)    
USE [WebTest]  DBCC SHRINKFILE (N'WebTest_Log' , 0, TRUNCATEONLY)    
USE [Education]  DBCC SHRINKFILE (N'Education_Log' , 0, TRUNCATEONLY)    
USE [TrendsDev]  DBCC SHRINKFILE (N'TrendsProd_Log' , 0, TRUNCATEONLY)    
USE [MSCRM_CONFIG]  DBCC SHRINKFILE (N'MSCRM_CONFIG_log' , 0, TRUNCATEONLY)    
USE [California_Association_of_Realtors_MSCRM]  DBCC SHRINKFILE (N'California_Association_of_Realtors_MSCRM_log' , 0, TRUNCATEONLY)    
USE [view-eventdb]  DBCC SHRINKFILE (N'view-eventdb_log' , 0, TRUNCATEONLY)    
USE [FPAUDIT]  DBCC SHRINKFILE (N'FPAUDIT_Log' , 0, TRUNCATEONLY)    
USE [FPASSURE_DYNAMICS]  DBCC SHRINKFILE (N'FPASSURE_DYNAMICS_Log' , 0, TRUNCATEONLY)    
USE [MR2012]  DBCC SHRINKFILE (N'ManagementReporter_Log' , 0, TRUNCATEONLY)    
USE [KAV]  DBCC SHRINKFILE (N'KAV_log' , 0, TRUNCATEONLY)    
USE [SCRIBEINTERNAL]  DBCC SHRINKFILE (N'SCRIBEINTERNAL_LOG' , 0, TRUNCATEONLY)    
USE [AIR]  DBCC SHRINKFILE (N'AIR_Log' , 0, TRUNCATEONLY)    
USE [DRE]  DBCC SHRINKFILE (N'DRE_Log' , 0, TRUNCATEONLY)    
USE [distribution]  DBCC SHRINKFILE (N'distribution_log' , 0, TRUNCATEONLY)    
USE [UMS]  DBCC SHRINKFILE (N'UMS_Log' , 0, TRUNCATEONLY)    
USE [CAR_MSCRM]  DBCC SHRINKFILE (N'California_Association_of_Realtors_MSCRM_log' , 0, TRUNCATEONLY)    
USE [VIM_UMDB]  DBCC SHRINKFILE (N'VIM_UMDB_log' , 0, TRUNCATEONLY)    
USE [VIM_VCDB]  DBCC SHRINKFILE (N'VIM_VCDB_log' , 0, TRUNCATEONLY)    
USE [Connectship]  DBCC SHRINKFILE (N'Connectship_log' , 0, TRUNCATEONLY)    
USE [SendSuite Live]  DBCC SHRINKFILE (N'SendSuite Live_log' , 0, TRUNCATEONLY)    
USE [composer_db]  DBCC SHRINKFILE (N'composer_db_log' , 0, TRUNCATEONLY)    
USE [Cheaters]  DBCC SHRINKFILE (N'Cheaters_log' , 0, TRUNCATEONLY)    
USE [Cheaters-22nd]  DBCC SHRINKFILE (N'Cheaters_log' , 0, TRUNCATEONLY)    
USE [I3_IC_V4_IVRDATA]  DBCC SHRINKFILE (N'I3_IC_V4_IVRDATA_log' , 0, TRUNCATEONLY)    
USE [IT_Inventory]  DBCC SHRINKFILE (N'IT_Inventory_log' , 0, TRUNCATEONLY)    